### PR TITLE
returning and then print

### LINKED ISSUE #241: refactor discover pkg apis
Currently discover pkg apis i.e. `ConvertPolicy()` and `Policy()` and are not usable outside. The discovered policies are printed to `stdout` only. if we can make these apis to return the encoded policies then we can utilize them outside. for example, we can leverage these apis in ginkgo based auto-testing framework for `discovery-engine` where it will no longer required to handle policy data from standard output.

### PR DESCRIPTION
**Pull request by Prateeknandle**
Signed-off-by: Prateeknandle <prateeknandle@gmail.com>
closes #241 
refractoring discover api:
changes : 
- returning the discover policy output when `ConvertPolicy()` is called
- printing the output is now done by `Policy()` func, when comand is used

after this we can use discover api to get the discovered policies rather than executing command in code.

### CODE REVIEW

**Comment by Prateeknandle** [comment]
opened pr for go-sec failing issue

**Comment by Prateeknandle** [comment]
why ginkgo-test is failing? ig it is not ecause of my changes

**Comment by Prateeknandle** [comment]
@PrimalPimmy can you run the ginkgo test workflow again, it is working locally

**Comment by PrimalPimmy** [comment]
I'm not sure if it'll run the updated workflow, let's see.

**Comment by Prateeknandle** [comment]
@PrimalPimmy  you can review the pr

**Comment by PrimalPimmy** [comment]
@Prateeknandle can you the linting issue that is shown in the files changed section?

**Comment by Prateeknandle** [comment]
> @Prateeknandle can you the linting issue that is shown in the files changed section?

updated

**Comment by Prateeknandle** [comment]
@rksharma95 can we merge this?

**Review by rksharma95 — APPROVED** [review]
LGTM :+1:

**Comment by Prateeknandle** [comment]
@rksharma95 do we need to squah `merge` commit also?

**Comment by rksharma95** [comment]
> @rksharma95 do we need to squah `merge` commit also?

don't squash instead undo it and do `fetch and rebase` then it will not result in another commit.

**Pull request merged**
