### PR TITLE
checking err for stream close

### PR DESCRIPTION
**Pull request by Prateeknandle**
Signed-off-by: Prateeknandle <prateeknandle@gmail.com>
go-sec ci workflow fails for pr [https://github.com/kubearmor/kubearmor-client/pull/260](https://github.com/kubearmor/kubearmor-client/pull/260), therefore opening this pr to solve the err while closing io streams

### CODE REVIEW

**Comment by PrimalPimmy** [comment]
@Prateeknandle can you fix the gofmt issues?

**Comment by Prateeknandle** [comment]
@PrimalPimmy addressed gofmt issue

**Comment by Prateeknandle** [comment]
are these ginkgo-tests flaky?

**Comment by PrimalPimmy** [comment]
@Prateeknandle all recent PRs have been failing for some reason. karmor recommend is detecting one less policy than what is required.

**Comment by PrimalPimmy** [comment]
LGTM

**Review by rksharma95 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
