### PR TITLE
fix: recommend

### PR DESCRIPTION
**Pull request by jokestax**
## Description
check if the auth hash is empty which otherwise throws a panic error

## Fixes

[Link to issue](https://github.com/kubearmor/kubearmor-client/issues/459)

## Testing
Build the binary locally,and run "./kubearmor-client recommend"

### CODE REVIEW

**Comment by jokestax** [comment]
@DelusionalOptimist  @daemon1024 please review :)

**Review by daemon1024 — APPROVED** [review]

**Comment by Aryan-sharma11** [comment]
Hi @jokestax, kindly rebase this PR to resolve the CI issue.

**Comment by jokestax** [comment]
@Aryan-sharma11 done ✅

**Review by Aryan-sharma11 — APPROVED** [review]

**Comment by Aryan-sharma11** [comment]
> Can we get this into a release please?
Created the release with this fix.

**Pull request merged**
