### PR TITLE
updating ginkgo test based on updated policy-template

### PR DESCRIPTION
**Pull request by Prateeknandle**
Signed-off-by: Prateeknandle <prateeknandle@gmail.com>

### CODE REVIEW

**Comment by vishnusomank** [comment]
hey @Prateeknandle rather than reducing the number of matched policies it'll be better if you can update the `xx-least-functionality-execute-package-management-process-in-container.yaml` under `tests/recommend/res/out/wordpress-mysql-wordpress` and `tests/recommend/res/out/ubuntu-18-04` with this [yaml](https://github.com/kubearmor/policy-templates/blob/release/generic/system/ksp-nist-si-4-execute-package-management-process-in-container.yaml)
cc: @PrimalPimmy

**Comment by Prateeknandle** [comment]
@vishnusomank updated the pr

**Comment by PrimalPimmy** [comment]
@vishnusomank can you check now if it's alright?

**Review by vishnusomank — APPROVED** [review]
LGTM

**Comment by Prateeknandle** [comment]
can we merge this?

**Comment by vishnusomank** [comment]
> can we merge this?

can you squash the commits?

**Comment by Prateeknandle** [comment]
> > can we merge this?
> 
> can you squash the commits?

done

**Comment by Prateeknandle** [comment]
@vishnusomank can we merge this, there are some prs depending on it.

**Pull request merged**
