### PR TITLE
Feat: added postUpdate option in Renovate for go tidy

### PR DESCRIPTION
**Pull request by EraKin575**
Solves #428 

With this configuration, Renovate will automatically tidy your Go modules after each dependency update, ensuring that your go.sum file only contains necessary entries and is free from clutter associated with previous versions of your dependencies.

### CODE REVIEW

**Comment by EraKin575** [comment]
@kranurag7 please review

**Review by kranurag7 — CHANGES_REQUESTED** [review]
As of now, `renovate-config-validator` shows me the following warning. I understand that the config is backward compatible but it will be great if you can update it and this way we will avoid the warning as well. 

```bash
$ renovate-config-validator renovate.json
 INFO: Validating renovate.json
 WARN: Config migration necessary
       "oldConfig": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "extends": ["config:base"],
         "constraints": {"go": "1.22"},
         "ignorePresets": [":prHourlyLimit2"],
         "reviewers": ["team:maintainers"],
         "postUpdateOptions": ["gomodTidy"]
       },
       "newConfig": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "extends": ["config:recommended"],
         "constraints": {"go": "1.22"},
         "ignorePresets": [":prHourlyLimit2"],
         "reviewers": ["team:maintainers"],
         "postUpdateOptions": ["gomodTidy"]
       }
 INFO: Config validated successfully
```

**Comment by kranurag7** [comment]
Below is the diff: 
```diff
-    "config:base"
+    "config:recommended"
```
And then the validator is happy. 

```bash
$ renovate-config-validator renovate.json
 INFO: Validating renovate.json
 INFO: Config validated successfully
```

**Comment by kranurag7** [comment]
@EraKin575 small nit, can you please squash the commits?

**Review by kranurag7 — APPROVED** [review]
Thank you @EraKin575 for working on this. I'll squash the commits from my end.

**Comment by EraKin575** [comment]
made my first contribution to kubearmor!

**Pull request merged**
