### PR TITLE
fix(recommend): Ensure karmor recommend supports Docker v26 by updating static policies and refactor extractTar function

### PR DESCRIPTION
**Pull request by Ishaanj18**
fixes: [#444](https://github.com/kubearmor/kubearmor-client/issues/444)

1.  Modified policies under `res/out` directory according to the new policy template release.
2.  Added logic to check if the file path within the tar archive starts with "blobs/". If a file path starts with "blobs/", the function recursively calls extractTar to extract its contents.

### CODE REVIEW

**Review by Prateeknandle — COMMENTED** [review]
@Ishaanj18 Thanks for the PR, code looks good, tested locally as well.
Please handle few nits mentioned below

**Comment by Prateeknandle** [comment]
And also please squash the commits

**Comment by Ishaanj18** [comment]
Hey @Prateeknandle I am not able to see any reviews regarding code changes

**Comment by Prateeknandle** [comment]
> Hey @Prateeknandle I am not able to see any reviews regarding code changes

sorry, forgot to submit the review

**Review by Prateeknandle — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
