### PR TITLE
updated deployment to get kubearmor hostname fix

### PR DESCRIPTION
**Pull request by nyrahul**
Ref: kubearmor/kubearmor#736

Signed-off-by: Rahul Jadhav <nyrahul@gmail.com>

### CODE REVIEW

**Comment by daemon1024** [comment]
We do need an automatic CI trigger on changes merged to individual package, to trigger dependency update PR 😅

**Comment by nyrahul** [comment]
Auto-updating the dependency is also a risky affair, hence I am ok with this. WDYT?

**Comment by daemon1024** [comment]
We just raise a PR, would need a review from maintainers before we merge and create release. 

But with the frequency we have right now, I guess it should be fine for now.

**Comment by nyrahul** [comment]
That will be great, if a bot could raise a PR for maintainers to review!

**Pull request merged**
