### PR TITLE
Remove empty type for json and yaml format

### PR DESCRIPTION
**Pull request by seswarrajan**
Signed-off-by: Eswar Rajan Subramanian <eswar@accuknox.com>

### CODE REVIEW

**Comment by daemon1024** [comment]
We used a different `json` library which helped in omitting empty structs while marshaling

Ref 
- [kubearmor/KubeArmor@`145c00e` (#486)](https://github.com/kubearmor/KubeArmor/pull/486/commits/145c00e60b766a21a6f15484ab43fc05339028a8#diff-4385480037f9263a9c2757fc121e2cab8414230a8a46ff10b9351c6133335b5e)
- https://github.com/clarketm/json#features

**Comment by seswarrajan** [comment]
> We used a different `json` library which helped in omitting empty structs while marshaling. This should eliminate the use of Regex Here.
> 
> Ref
> 
> * [kubearmor/KubeArmor@`145c00e` (#486)](https://github.com/kubearmor/KubeArmor/pull/486/commits/145c00e60b766a21a6f15484ab43fc05339028a8#diff-4385480037f9263a9c2757fc121e2cab8414230a8a46ff10b9351c6133335b5e)
> * https://github.com/clarketm/json#features

Thanks @daemon1024

**Review by daemon1024 — APPROVED** [review]
LGTM.

Please drop the irrelevant commits from the PR. Thanks.

**Comment by Ankurk99** [comment]
LGTM

**Review by nyrahul — APPROVED** [review]
LGTM

**Pull request merged**
